service: breathe-backend
org: theopenthread
app: breathe-app

frameworkVersion: '3'

useDotenv: true  # ✅ This ensures .env is loaded early

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1 # or your preferred region
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    MONGODB_USERNAME: ${env:MONGODB_USERNAME}
    MONGODB_PWD: ${env:MONGODB_PWD}
    STREAM_API_KEY: ${env:STREAM_API_KEY}
    STREAM_SECRET: ${env:STREAM_SECRET}
  # remove dynamo db for now
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "dynamodb:*"
  #     Resource: "*"

functions:
  createReflection:
    handler: src/handlers/createReflection.handler
    events:
      - http:
          path: reflections
          method: post
          # cors: ${self:custom.defaultCors}
          cors: true
  getPeerReflections:
    handler: src/handlers/getPeerReflections.handler
    events:
      - http:
          path: peer-reflections
          method: get
          cors: true
  getUserReflections:
    handler: src/handlers/getUserReflections.handler
    events:
      - http:
          path: user-reflections
          method: get
          cors: true
  sendMoment:
    handler: src/handlers/sendMoment.handler
    events:
      - http:
          path: send-moment
          method: post
          cors: true
  getUserMoments:
    handler: src/handlers/getUserMoments.handler
    events:
      - http:
          path: moments
          method: get
          cors: true
  sendWalkRequest:
    handler: src/handlers/sendWalkRequest.handler
    events:
      - http:
          path: walk-together
          method: post
          cors: true
  getWalkRequests:
    handler: src/handlers/getWalkRequests.handler
    events:
      - http:
          path: walk-requests
          method: get
          cors: true
  acceptWalkRequest:
    handler: src/handlers/acceptWalkRequest.handler
    events:
      - http:
          path: walk-accept
          method: post
          cors: true
  declineWalkRequest:
    handler: src/handlers/declineWalkRequest.handler
    events:
      - http:
          path: walk-decline
          method: post
          cors: true
  getWalkRooms:
    handler: src/handlers/getWalkRooms.handler
    events:
      - http:
          path: walk-rooms
          method: get
          cors: true
  getChatToken:
    handler: src/handlers/getChatToken.handler
    events:
      - http:
          path: chat-token
          method: get
          cors: true
  leaveWalkRoom:
    handler: src/handlers/leaveWalkRoom.handler
    events:
      - http:
          path: walk-leave
          method: post
          cors: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node
    concurrency: 10
    watch:
      pattern: ["src/**/*.ts"] # Watch your source directory
      ignore: ["node_modules/**"]
  serverless-offline:
    httpPort: 8000
  dotenv:
    path: .env
  defaultCors:
    origin: '*'
    headers:
      - Content-Type
      - Authorization
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
    allowCredentials: false